**Obtencion de población mayor a 60 años por alcaldía**

In [98]:
import pandas as pd

In [99]:
pob_2015 = pd.read_excel("../../data/raw/2015/pob_eic2015_cdmx.xls", sheet_name="02", header=6)
pob_2015.head()

,Entidad federativa,Delegación,Grupos quinquenales de edad,Estimador,Población total,Hombres,Mujeres
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,09 Ciudad de México,Total,Total,Valor,8.918653e+06,4.231650e+06,4.687003e+06
2,09 Ciudad de México,Total,Total,Error estándar,1.351122e+05,6.463080e+04,7.117626e+04
3,09 Ciudad de México,Total,Total,Límite inferior de confianza,8.696349e+06,4.125311e+06,4.569895e+06
4,09 Ciudad de México,Total,Total,Límite superior de confianza,9.140957e+06,4.337989e+06,4.804111e+06

In [100]:
pob_2015.drop(index=0, inplace=True)
pob_2015.head()

,Entidad federativa,Delegación,Grupos quinquenales de edad,Estimador,Población total,Hombres,Mujeres
1,09 Ciudad de México,Total,Total,Valor,8.918653e+06,4.231650e+06,4.687003e+06
2,09 Ciudad de México,Total,Total,Error estándar,1.351122e+05,6.463080e+04,7.117626e+04
3,09 Ciudad de México,Total,Total,Límite inferior de confianza,8.696349e+06,4.125311e+06,4.569895e+06
4,09 Ciudad de México,Total,Total,Límite superior de confianza,9.140957e+06,4.337989e+06,4.804111e+06
5,09 Ciudad de México,Total,Total,Coeficiente de variación,1.514939e+00,1.527319e+00,1.518588e+00

In [101]:
pob_2015.rename(columns={"Entidad federativa": "entidad", "Delegación": "mun", "Grupos quinquenales de edad": "rangos_edad", "Población total": "poblacion"}, inplace=True)

In [102]:
rangos_edad = ["60-64 años", "65-69 años", "70-74 años", "75 años y más"]

In [103]:
pob_2015 = pob_2015[(pob_2015["mun"] != "Total") & (pob_2015["rangos_edad"].isin(rangos_edad)) & (pob_2015["Estimador"] == "Valor")]
pob_2015

,entidad,mun,rangos_edad,Estimador,poblacion,Hombres,Mujeres
187,09 Ciudad de México,010 Álvaro Obregón,60-64 años,Valor,33072.0,15157.0,17915.0
193,09 Ciudad de México,010 Álvaro Obregón,65-69 años,Valor,25487.0,11744.0,13743.0
199,09 Ciudad de México,010 Álvaro Obregón,70-74 años,Valor,17559.0,7627.0,9932.0
205,09 Ciudad de México,010 Álvaro Obregón,75 años y más,Valor,27199.0,10797.0,16402.0
295,09 Ciudad de México,002 Azcapotzalco,60-64 años,Valor,19857.0,8506.0,11351.0
...,...,...,...,...,...,...,...
1717,09 Ciudad de México,017 Venustiano Carranza,75 años y más,Valor,20814.0,7573.0,13241.0
1801,09 Ciudad de México,013 Xochimilco,60-64 años,Valor,16227.0,7399.0,8828.0
1807,09 Ciudad de México,013 Xochimilco,65-69 años,Valor,12807.0,5969.0,6838.0
1813,09 Ciudad de México,013 Xochimilco,70-74 años,Valor,8615.0,3697.0,4918.0
1819,09 Ciudad de México,013 Xochimilco,75 años y más,Valor,9843.0,4155.0,5688.0

In [104]:
pob_2015 = pob_2015[["entidad","mun","rangos_edad","poblacion"]]
pob_2015

                  entidad                      mun    rangos_edad  poblacion
187   09 Ciudad de México       010 Álvaro Obregón     60-64 años    33072.0
193   09 Ciudad de México       010 Álvaro Obregón     65-69 años    25487.0
199   09 Ciudad de México       010 Álvaro Obregón     70-74 años    17559.0
205   09 Ciudad de México       010 Álvaro Obregón  75 años y más    27199.0
295   09 Ciudad de México         002 Azcapotzalco     60-64 años    19857.0
...                   ...                      ...            ...        ...
1717  09 Ciudad de México  017 Venustiano Carranza  75 años y más    20814.0
1801  09 Ciudad de México           013 Xochimilco     60-64 años    16227.0
1807  09 Ciudad de México           013 Xochimilco     65-69 años    12807.0
1813  09 Ciudad de México           013 Xochimilco     70-74 años     8615.0
1819  09 Ciudad de México           013 Xochimilco  75 años y más     9843.0

[64 rows x 4 columns]

In [105]:
pob_2015["entidad"] = pob_2015["entidad"].str.extract("(\d*)\s")
pob_2015["mun"] = pob_2015["mun"].str.extract("(\d*)\s")
pob_2015.head(5)

/tmp/ipykernel_134968/1369844178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_2015["entidad"] = pob_2015["entidad"].str.extract("(\d*)\s")
/tmp/ipykernel_134968/1369844178.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_2015["mun"] = pob_2015["mun"].str.extract("(\d*)\s")

    entidad  mun    rangos_edad  poblacion
187      09  010     60-64 años    33072.0
193      09  010     65-69 años    25487.0
199      09  010     70-74 años    17559.0
205      09  010  75 años y más    27199.0
295      09  002     60-64 años    19857.0

In [106]:
pob_2015_60mas = pob_2015.groupby(["entidad","mun"], as_index=False)["poblacion"].sum()
pob_2015_60mas.rename(columns={"poblacion": "p_60ymas_mun"}, inplace=True)
pob_2015_60mas

   entidad  mun  p_60ymas_mun
0       09  002       68096.0
1       09  003      109218.0
2       09  004       18829.0
3       09  005      183410.0
4       09  006       58140.0
5       09  007      222114.0
6       09  008       30790.0
7       09  009       11996.0
8       09  010      103317.0
9       09  011       36100.0
10      09  012       89699.0
11      09  013       47492.0
12      09  014       80346.0
13      09  015       83748.0
14      09  016       62001.0
15      09  017       71156.0

**Obtención de población mayor a 60 años por AGEB (estimación)**

In [107]:
r2010 = pd.read_csv("../../data/processed/results2010.csv", dtype={"entidad": str, "mun": str, "loc": str})
r2020 = pd.read_csv("../../data/processed/results2020.csv", dtype={"entidad": str, "mun": str, "loc": str})

In [108]:
r2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2432 entries, 0 to 2431
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             2432 non-null   int64
 1   entidad                2432 non-null   object
 2   nom_ent                2432 non-null   object
 3   mun                    2432 non-null   object
 4   nom_mun                2432 non-null   object
 5   loc                    2432 non-null   object
 6   nom_loc                2432 non-null   object
 7   ageb                   2432 non-null   object
 8   mza                    2432 non-null   int64
 9   pobtot                 2432 non-null   int64
 10  p_60ymas               2420 non-null   float64
 11  cvegeo                 2432 non-null   object
 12  cantidad_serv_enf_dom  2432 non-null   float64
 13  cantidad_asilos        2432 non-null   float64
 14  p_60ymas_mun           2432 non-null   float64
 15  concentracion          2420 non-null   float64
dtypes: float64(5), int64(3), object(8)
memory usage: 304.1+ KB

In [109]:
r2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2433 entries, 0 to 2432
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             2433 non-null   int64
 1   entidad                2433 non-null   object
 2   nom_ent                2433 non-null   object
 3   mun                    2433 non-null   object
 4   nom_mun                2433 non-null   object
 5   loc                    2433 non-null   object
 6   nom_loc                2433 non-null   object
 7   ageb                   2433 non-null   object
 8   mza                    2433 non-null   int64
 9   pobtot                 2433 non-null   int64
 10  p_60ymas               2416 non-null   float64
 11  cvegeo                 2433 non-null   object
 12  cantidad_serv_enf_dom  2433 non-null   float64
 13  cantidad_asilos        2433 non-null   float64
 14  p_60ymas_mun           2433 non-null   float64
 15  concentracion          2416 non-null   float64
dtypes: float64(5), int64(3), object(8)
memory usage: 304.2+ KB

In [110]:
len(r2010)

2432

In [111]:
len(r2020)

2433

Veamos que AGEBs estan presentes en un año y no en el otro. Las eliminaremos ya que utilizaremos el mapa de 2020.

In [112]:
a = r2010[["entidad","cvegeo","concentracion"]].merge(r2020[["entidad","cvegeo","concentracion"]], on="cvegeo", how="outer")

In [113]:
a[a["entidad_y"].isna()]

     entidad_x         cvegeo  concentracion_x entidad_y  concentracion_y
515         09  0900500012502         0.000027       NaN              NaN
2240        09  0901600010938         0.000336       NaN              NaN

In [114]:
a.drop(index=[515,2240], inplace=True)

In [115]:
a["concentracion_prom"] = (a["concentracion_x"] + a["concentracion_y"])/2

In [116]:
import numpy as np

AGEBs totalmente confidenciales

In [117]:
a.loc[(a["concentracion_x"].isna()) & (a["concentracion_y"].isna()),"concentracion_prom"] = np.nan

In [118]:
a.loc[(a["concentracion_x"].isna()) & (a["concentracion_y"].notna()), "concentracion_prom"] = a["concentracion_y"]

In [119]:
a.loc[(a["concentracion_x"].notna()) & (a["concentracion_y"].isna()), "concentracion_prom"] = a["concentracion_x"]

In [120]:
a = a[["cvegeo","concentracion_prom"]]
a.sample(5)

             cvegeo  concentracion_prom
1945  0901400010488            0.015580
2150  090150001152A            0.006502
911   0900700012846            0.003078
486   0900500012199            0.004088
1321  0901000010741            0.005066

Tomamos la lista de AGEB 2020

In [121]:
merge2020 = r2020[["entidad", "nom_ent", "mun", "nom_mun", "loc", "nom_loc", "ageb", "cvegeo"]].merge(a, on="cvegeo", how="left")

In [122]:
merge2020.sample()

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,cvegeo,concentracion_prom
2044,09,Ciudad de México,015,Cuauhtémoc,0001,Total AGEB urbana,0466,0901500010466,0.019359

In [123]:
merge2020 = merge2020.merge(pob_2015_60mas[["mun", "p_60ymas_mun"]], on="mun", how="left")

In [124]:
merge2020[merge2020["concentracion_prom"].isna()]

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,cvegeo,concentracion_prom,p_60ymas_mun
636,09,Ciudad de México,006,Iztacalco,0001,Total AGEB urbana,0467,0900600010467,NaN,58140.0
1455,09,Ciudad de México,010,Álvaro Obregón,0001,Total AGEB urbana,2381,0901000012381,NaN,103317.0
1702,09,Ciudad de México,012,Tlalpan,0001,Total AGEB urbana,1759,0901200011759,NaN,89699.0
1896,09,Ciudad de México,013,Xochimilco,0001,Total AGEB urbana,1578,0901300011578,NaN,47492.0
2201,09,Ciudad de México,016,Miguel Hidalgo,0001,Total AGEB urbana,0533,0901600010533,NaN,62001.0

In [125]:
merge2020["p_60ymas_est"] = merge2020["p_60ymas_mun"] * merge2020["concentracion_prom"]
merge2020.sample()

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,cvegeo,concentracion_prom,p_60ymas_mun,p_60ymas_est
2117,09,Ciudad de México,015,Cuauhtémoc,0001,Total AGEB urbana,120A,090150001120A,0.003807,83748.0,318.869194

In [126]:
pob_ageb_2015 = merge2020[["entidad", "nom_ent", "mun", "nom_mun", "loc", "nom_loc", "ageb", "cvegeo", "p_60ymas_est"]]
pob_ageb_2015.sample()

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,cvegeo,p_60ymas_est
55,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,067A,090020001067A,900.23152

**Obtención de servicios DENUE por AGEB**

*Servicios DENUE 2015* 
Clave - Descripción de categoría
* 621610 - Servicios de enfermería a domicilio
* 623311 - Asilos y otras residencias del sector privado para el cuidado de ancianos
* 623312 - Asilos y otras residencias del sector público para el cuidado de ancianos

In [127]:
denue_2015 = pd.read_csv("../../data/raw/2015/denue2015.csv")
denue_2015.info()

/tmp/ipykernel_134968/3971491166.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  denue_2015 = pd.read_csv("../../data/raw/2015/denue2015.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452347 entries, 0 to 452346
Data columns (total 41 columns):
 #   Column                                                   Non-Null Count   Dtype
---  ------                                                   --------------   -----
 0   ID                                                       452347 non-null  int64
 1   Nombre de la Unidad Económica                            452347 non-null  object
 2   Razón social                                             81909 non-null   object
 3   Código de la clase de actividad SCIAN                    452347 non-null  int64
 4   Nombre de clase de la actividad                          452347 non-null  object
 5   Descripcion estrato personal ocupado                     452347 non-null  object
 6   Tipo de vialidad                                         448841 non-null  object
 7   Nombre de la vialidad                                    451879 non-null  object
 8   Tipo de entre vialidad 1                                 445559 non-null  object
 9   Nombre de entre vialidad 1                               451294 non-null  object
 10  Tipo de entre vialidad 2                                 445228 non-null  object
 11  Nombre de entre vialidad 2                               451277 non-null  object
 12  Tipo de entre vialidad 3                                 444475 non-null  object
 13  Nombre de entre vialidad 3                               451125 non-null  object
 14  Número exterior o kilómetro                              452347 non-null  int64
 15  Letra exterior                                           186136 non-null  object
 16  Edificio                                                 21067 non-null   object
 17  Edificio Piso                                            36559 non-null   object
 18  Número interior                                          452346 non-null  float64
 19  Letra interior                                           73495 non-null   object
 20  Tipo de asentamiento humano                              451655 non-null  object
 21  Nombre de asentamiento humano                            452320 non-null  object
 22  Tipo centro comercial                                    73217 non-null   object
 23  Corredor industrial, centro comercial o mercado público  86790 non-null   object
 24  Número de local                                          76700 non-null   object
 25  Código Postal                                            451726 non-null  object
 26  Clave entidad                                            452347 non-null  int64
 27  Entidad federativa                                       452347 non-null  object
 28  Clave municipio                                          452347 non-null  int64
 29  Municipio                                                452347 non-null  object
 30  Clave localidad                                          452347 non-null  int64
 31  Localidad                                                452347 non-null  object
 32  Área geoestadística básica                               452347 non-null  object
 33  Manzana                                                  452347 non-null  int64
 34  Número de teléfono                                       208227 non-null  float64
 35  Correo electrónico                                       50013 non-null   object
 36  Sitio en Internet                                        25671 non-null   object
 37  Tipo de establecimiento                                  452347 non-null  object
 38  Latitud                                                  452347 non-null  float64
 39  Longitud                                                 452347 non-null  float64
 40  Fecha de incorporación al DENUE                          452347 non-null  object
dtypes: float64(4), int64(7), object(30)
memory usage: 141.5+ MB

In [128]:
denue_2015 = denue_2015[["Código de la clase de actividad SCIAN", "Clave entidad", "Clave municipio", "Clave localidad", "Área geoestadística básica "]]
denue_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452347 entries, 0 to 452346
Data columns (total 5 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   Código de la clase de actividad SCIAN  452347 non-null  int64
 1   Clave entidad                          452347 non-null  int64
 2   Clave municipio                        452347 non-null  int64
 3   Clave localidad                        452347 non-null  int64
 4   Área geoestadística básica             452347 non-null  object
dtypes: int64(4), object(1)
memory usage: 17.3+ MB

In [129]:
denue_2015.rename(columns={"Código de la clase de actividad SCIAN": "codigo_act", "Clave entidad": "entidad", "Clave municipio": "mun", "Clave localidad": "loc", "Área geoestadística básica ": "ageb"}, inplace=True)

In [130]:
denue_2015["entidad"] = denue_2015["entidad"].astype(str).str.zfill(2)
denue_2015["mun"] = denue_2015["mun"].astype(str).str.zfill(3)
denue_2015["loc"] = denue_2015["loc"].astype(str).str.zfill(4)
denue_2015["ageb"] = denue_2015["ageb"].astype(str).str.zfill(4)
denue_2015.sample()

        codigo_act entidad  mun   loc  ageb
122767      461130      09  011  0011  1037

In [131]:
denue_2015["cvegeo"] = (denue_2015["entidad"] + denue_2015["mun"] + denue_2015["loc"] + denue_2015["ageb"])
denue_2015.sample()

        codigo_act entidad  mun   loc  ageb         cvegeo
144788      466111      09  014  0001  051A  090140001051A

In [132]:
serv_enf_dom = denue_2015[denue_2015["codigo_act"] == 621610]

In [133]:
serv_enf_dom = serv_enf_dom.groupby("cvegeo", as_index=False)["codigo_act"].count()
serv_enf_dom.rename(columns={"codigo_act":"cantidad_serv_enf_dom"}, inplace=True)
serv_enf_dom

           cvegeo  cantidad_serv_enf_dom
0   0900200010839                      1
1   0900500011415                      1
2   0900500011557                      1
3   090050001224A                      1
4   0900600010382                      1
5   0900700010572                      1
6   0900700012174                      1
7   0900700013825                      2
8   090100001014A                      1
9   0901000011260                      2
10  0901200010695                      1
11  0901200011104                      1
12  0901400010064                      1
13  0901400010100                      1
14  0901400010261                      1
15  090140001101A                      1
16  0901500010729                      1
17  0901500010926                      1
18  0901500011002                      1
19  0901500011341                      1
20  0901600010660                      1
21  0901600010745                      1
22  0901700010634                      1
23  0901700011261                      1

In [134]:
asilos = denue_2015[denue_2015["codigo_act"].isin([623311, 623312])]
asilos

        codigo_act entidad  mun   loc  ageb         cvegeo
303285      623312      09  014  0001  0384  0901400010384
303298      623312      09  014  0001  0204  0901400010204
303906      623311      09  005  0001  1754  0900500011754
303907      623311      09  008  0001  0283  0900800010283
303908      623311      09  002  0001  0491  0900200010491
...            ...     ...  ...   ...   ...            ...
324059      623311      09  014  0001  0736  0901400010736
324060      623311      09  016  0001  1029  0901600011029
324061      623311      09  012  0001  0958  0901200010958
324062      623311      09  002  0001  0345  0900200010345
324706      623311      09  002  0001  0699  0900200010699

[79 rows x 6 columns]

In [135]:
asilos = asilos.groupby("cvegeo", as_index=False)["codigo_act"].count()
asilos.rename(columns={"codigo_act":"cantidad_asilos"}, inplace=True)
asilos

           cvegeo  cantidad_asilos
0   0900200010345                2
1   0900200010491                1
2   0900200010699                1
3   0900200010792                1
4   0900300010041                1
..            ...              ...
64  0901600010177                1
65  0901600010942                1
66  0901600011029                1
67  0901600011175                1
68  0901700010920                1

[69 rows x 2 columns]

Como de las agebs que no tienen establecimientos, es porque no hay información en el denue, entonces se infiere que no hay esos servicios, por lo que en esas rellenaremos con 0.

In [136]:
res = pob_ageb_2015.merge(serv_enf_dom, on="cvegeo", how="left")
res["cantidad_serv_enf_dom"] = res["cantidad_serv_enf_dom"].fillna(0)

In [137]:
res = res.merge(asilos, on="cvegeo", how="left")
res["cantidad_asilos"] = res["cantidad_asilos"].fillna(0)
res

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,cvegeo,p_60ymas_est,cantidad_serv_enf_dom,cantidad_asilos
0,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0010,0900200010010,848.744226,0.0,0.0
1,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0025,0900200010025,1146.864149,0.0,0.0
2,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,003A,090020001003A,946.751546,0.0,0.0
3,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0044,0900200010044,1088.619413,0.0,0.0
4,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0097,0900200010097,558.552025,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2428,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1488,0901700011488,83.604931,0.0,0.0
2429,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1492,0901700011492,79.129931,0.0,0.0
2430,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1505,0901700011505,225.725635,0.0,0.0
2431,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,151A,090170001151A,228.015630,0.0,0.0
2432,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1524,0901700011524,652.831079,0.0,0.0

In [138]:
res.to_csv("../../data/processed/results2015.csv")