In [1]:
import pandas as pd

**Obtención de poblacion mayor a 60 años por alcaldía**

In [2]:
pob_2010 = pd.read_excel("../../data/raw/2010/pob_cpv2010_cdmx.xls", header=6, usecols=["Entidad federativa", "Delegación", "Sexo","Grupos quinquenales de edad", "Población total1"])
pob_2010.head(5)

,Entidad federativa,Delegación,Sexo,Grupos quinquenales de edad,Población total1
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,09 Distrito Federal,Total,Total,Total,8851080.0
3,09 Distrito Federal,Total,Total,00-04 años,618245.0
4,09 Distrito Federal,Total,Total,05-09 años,658948.0

In [3]:
pob_2010.drop(index=[0,1], inplace=True)

In [4]:
pob_2010.rename(columns={"Entidad federativa": "entidad", "Delegación": "mun", "Sexo":"sexo", "Grupos quinquenales de edad": "rangos_edad", "Población total1": "poblacion"}, inplace=True)

In [5]:
pob_2010 = pob_2010[(pob_2010["mun"] != "Total") & (pob_2010["sexo"] == "Total")]
pob_2010.sample(5)

                  entidad             mun   sexo      rangos_edad  poblacion
990   09 Distrito Federal     012 Tlalpan  Total  No especificado    17000.0
634   09 Distrito Federal  007 Iztapalapa  Total       50-54 años    96692.0
625   09 Distrito Federal  007 Iztapalapa  Total       05-09 años   153575.0
1124  09 Distrito Federal  013 Xochimilco  Total       85-89 años     1585.0
983   09 Distrito Federal     012 Tlalpan  Total       70-74 años    11353.0

In [6]:
rangos_edad = ["60-64 años", "65-69 años", "70-74 años", "75-79 años", "80-84 años", "85-89 años", "90-94 años", "95-99 años", "100 años y más"]

In [7]:
pob_2010 = pob_2010[pob_2010["rangos_edad"].isin(rangos_edad)]
pob_2010.head(5)

                entidad                 mun   sexo rangos_edad  poblacion
84  09 Distrito Federal  010 Álvaro Obregón  Total  60-64 años    25336.0
85  09 Distrito Federal  010 Álvaro Obregón  Total  65-69 años    17833.0
86  09 Distrito Federal  010 Álvaro Obregón  Total  70-74 años    14167.0
87  09 Distrito Federal  010 Álvaro Obregón  Total  75-79 años     9691.0
88  09 Distrito Federal  010 Álvaro Obregón  Total  80-84 años     6577.0

In [8]:
pob_2010["entidad"] = pob_2010["entidad"].str.extract("(\d*)\s")
pob_2010["mun"] = pob_2010["mun"].str.extract("(\d*)\s")
pob_2010.head(5)

   entidad  mun   sexo rangos_edad  poblacion
84      09  010  Total  60-64 años    25336.0
85      09  010  Total  65-69 años    17833.0
86      09  010  Total  70-74 años    14167.0
87      09  010  Total  75-79 años     9691.0
88      09  010  Total  80-84 años     6577.0

In [9]:
pob_2010_60mas = pob_2010.groupby(["entidad","mun"], as_index=False)["poblacion"].sum()
pob_2010_60mas.rename(columns={"poblacion": "p_60ymas_mun"}, inplace=True)
pob_2010_60mas

   entidad  mun  p_60ymas_mun
0       09  002       56484.0
1       09  003       87269.0
2       09  004       14212.0
3       09  005      148472.0
4       09  006       50232.0
5       09  007      165731.0
6       09  008       24280.0
7       09  009        9716.0
8       09  010       79008.0
9       09  011       26955.0
10      09  012       66108.0
11      09  013       37396.0
12      09  014       60607.0
13      09  015       69563.0
14      09  016       50539.0
15      09  017       57076.0

**Obtención de población mayor a 60 años por AGEB**

Como podemos ver los campos que utilizaremos seran:
* Clave entidad federativa - ENTIDAD
* Entidad federativa - NOM_ENT
* Clave de municipio o demarcación territorial - MUN
* Municipio o demarcación territorial - NOM_MUN
* Clave de localidad - LOC
* Localidad	- NOM_LOC
* Clave del AGEB - AGEB
* Clave manzana - MZA
* Población total - POBTOT
* Población de 60 años y más - P_60YMAS

In [10]:
pob_ageb_2010 = pd.read_csv("../../data/raw/2010/pob_ageb_cpv2010_cdmx.csv", dtype={"entidad":str, "mun": str, "loc": str})
pob_ageb_2010

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,pobmas,...,vph_snbien,vph_radio,vph_tv,vph_refri,vph_lavad,vph_autom,vph_pc,vph_telef,vph_cel,vph_inter
0,09,Distrito Federal,000,Total del Distrito Federal,0000,Total de la entidad,0000,0,8851080,4233783,...,6250,2185469,2337884,2165900,1854623,1110374,1171631,1715772,1817230,936648
1,09,Distrito Federal,002,Azcapotzalco,0000,Total del municipio,0000,0,414711,196053,...,147,106564,112503,107269,93517,52913,60003,86750,88236,47225
2,09,Distrito Federal,002,Azcapotzalco,0001,Total de la localidad urbana,0000,0,414711,196053,...,147,106564,112503,107269,93517,52913,60003,86750,88236,47225
3,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0010,0,3424,1600,...,0,771,805,804,762,466,447,751,598,346
4,09,Distrito Federal,002,Azcapotzalco,0001,Azcapotzalco,0010,1,202,96,...,0,43,46,46,45,28,21,45,26,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65716,09,Distrito Federal,017,Venustiano Carranza,0001,Venustiano Carranza,1524,21,138,61,...,0,30,36,33,26,12,12,21,28,8
65717,09,Distrito Federal,017,Venustiano Carranza,0001,Venustiano Carranza,1524,22,143,71,...,0,33,39,35,29,17,13,27,30,7
65718,09,Distrito Federal,017,Venustiano Carranza,0001,Venustiano Carranza,1524,23,333,162,...,0,75,81,72,62,29,30,53,65,15
65719,09,Distrito Federal,017,Venustiano Carranza,0001,Venustiano Carranza,1524,24,202,90,...,*,46,51,47,36,20,24,35,35,17
65720,09,Distrito Federal,017,Venustiano Carranza,0001,Venustiano Carranza,1524,25,522,248,...,*,127,142,129,97,43,54,89,116,32

In [11]:
pob_ageb_2010 = pob_ageb_2010[["entidad", "nom_ent", "mun", "nom_mun", "loc", "nom_loc", "ageb", "mza", "pobtot", "p_60ymas"]]
pob_ageb_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65721 entries, 0 to 65720
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   entidad   65721 non-null  object
 1   nom_ent   65721 non-null  object
 2   mun       65721 non-null  object
 3   nom_mun   65721 non-null  object
 4   loc       65721 non-null  object
 5   nom_loc   65721 non-null  object
 6   ageb      65721 non-null  object
 7   mza       65721 non-null  int64
 8   pobtot    65721 non-null  int64
 9   p_60ymas  65721 non-null  object
dtypes: int64(2), object(8)
memory usage: 5.0+ MB

In [12]:
pob_ageb_2010["entidad"] = pob_ageb_2010["entidad"].str.zfill(2)
pob_ageb_2010["mun"] = pob_ageb_2010["mun"].str.zfill(3)
pob_ageb_2010["loc"] = pob_ageb_2010["loc"].str.zfill(4)
pob_ageb_2010["ageb"] = pob_ageb_2010["ageb"].str.zfill(4)

/tmp/ipykernel_155916/4237613857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2010["entidad"] = pob_ageb_2010["entidad"].str.zfill(2)
/tmp/ipykernel_155916/4237613857.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2010["mun"] = pob_ageb_2010["mun"].str.zfill(3)
/tmp/ipykernel_155916/4237613857.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2010["loc"] = pob_ageb_2010["loc"].str.zfill(4)
/tmp/ipykernel_155916/4237613857.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2010["ageb"] = pob_ageb_2010["ageb"].str.zfill(4)

In [13]:
pob_ageb_2010 = pob_ageb_2010[(pob_ageb_2010.ageb != "0000") & (pob_ageb_2010.mza == 0)]
pob_ageb_2010.sample(5)

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas
25947,09,Distrito Federal,007,Iztapalapa,0001,Total AGEB urbana,2511,0,932,170
62233,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,0013,0,4643,529
58615,09,Distrito Federal,015,Cuauhtémoc,0001,Total AGEB urbana,1089,0,2303,260
46305,09,Distrito Federal,011,Tláhuac,0024,Total AGEB urbana,0749,0,224,6
58063,09,Distrito Federal,015,Cuauhtémoc,0001,Total AGEB urbana,0818,0,249,28

Pasemos p_60ymas a numerico para poder operarla.

In [14]:
pob_ageb_2010["p_60ymas"] = pd.to_numeric(pob_ageb_2010["p_60ymas"], errors="coerce")

In [15]:
pob_ageb_2010[pob_ageb_2010["p_60ymas"].isna()]

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas
17959,09,Distrito Federal,006,Iztacalco,0001,Total AGEB urbana,0151,0,280,NaN
18641,09,Distrito Federal,006,Iztacalco,0001,Total AGEB urbana,0467,0,17,NaN
37433,09,Distrito Federal,009,Milpa Alta,0024,Total AGEB urbana,0651,0,77,NaN
37535,09,Distrito Federal,009,Milpa Alta,0029,Total AGEB urbana,0609,0,79,NaN
43299,09,Distrito Federal,010,Álvaro Obregón,0001,Total AGEB urbana,2381,0,61,NaN
46318,09,Distrito Federal,011,Tláhuac,0024,Total AGEB urbana,1520,0,78,NaN
49688,09,Distrito Federal,012,Tlalpan,0001,Total AGEB urbana,1759,0,7,NaN
50962,09,Distrito Federal,012,Tlalpan,0001,Total AGEB urbana,2371,0,38,NaN
53867,09,Distrito Federal,013,Xochimilco,0001,Total AGEB urbana,1243,0,52,NaN
54383,09,Distrito Federal,013,Xochimilco,0001,Total AGEB urbana,1578,0,44,NaN
59961,09,Distrito Federal,016,Miguel Hidalgo,0001,Total AGEB urbana,0196,0,62,NaN
60634,09,Distrito Federal,016,Miguel Hidalgo,0001,Total AGEB urbana,0533,0,9,NaN

Antes de ver que haremos con esos NaN haremos la clave unica geoestadítica por ageb

In [16]:
pob_ageb_2010["cvegeo"] = (pob_ageb_2010["entidad"] + pob_ageb_2010["mun"] + pob_ageb_2010["loc"] + pob_ageb_2010["ageb"])

In [17]:
pob_ageb_2010.sample(5)

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas,cvegeo
61993,09,Distrito Federal,016,Miguel Hidalgo,0001,Total AGEB urbana,1298,0,1766,284.0,0901600011298
35468,09,Distrito Federal,008,La Magdalena Contreras,0001,Total AGEB urbana,0048,0,2553,484.0,0900800010048
40288,09,Distrito Federal,010,Álvaro Obregón,0001,Total AGEB urbana,1186,0,3068,587.0,0901000011186
4954,09,Distrito Federal,003,Coyoacán,0001,Total AGEB urbana,0709,0,3311,570.0,0900300010709
1542,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0631,0,5242,759.0,0900200010631

**Obtención de servicios DENUE por AGEB**

*Servicios DENUE 2010* 
Clave - Descripción de categoría
* 621610 - Servicios de enfermería a domicilio
* 623311 - Asilos y otras residencias del sector privado para el cuidado de ancianos
* 623312 - Asilos y otras residencias del sector público para el cuidado de ancianos

In [18]:
denue_2010 = pd.read_csv("../../data/raw/2010/denue2010.csv", encoding="latin-1")
denue_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 416898 entries, 0 to 416897
Data columns (total 24 columns):
 #   Column                                                   Non-Null Count   Dtype
---  ------                                                   --------------   -----
 0   Nombre de la unidad económica                            416898 non-null  object
 1   Razón social                                             85697 non-null   object
 2   Código de la clase de actividad                          416898 non-null  int64
 3   Nombre de la clase de actividad                          416898 non-null  object
 4   Personal ocupado (estrato)                               416898 non-null  object
 5   Calle, avenida, andador, carretera, manzana u otro       416486 non-null  object
 6   Número exterior o km                                     416898 non-null  object
 7   Edificio, piso o nivel                                   37462 non-null   object
 8   Número o letra interior                                  78136 non-null   object
 9   Colonia, fraccionamiento, unidad habitacional o barrio   416881 non-null  object
 10  Corredor industrial, centro comercial o mercado público  88203 non-null   object
 11  Número de local                                          0 non-null       float64
 12  Código postal                                            416898 non-null  int64
 13  Entidad federativa                                       416898 non-null  object
 14  Municipio                                                416898 non-null  object
 15  Localidad                                                416898 non-null  object
 16  Área geoestadística básica                               416898 non-null  object
 17  Manzana                                                  416898 non-null  int64
 18  Número de teléfono                                       416898 non-null  int64
 19  Correo electrónico                                       8029 non-null    object
 20  Sitio en Internet                                        4311 non-null    object
 21  Tipo de unidad económica                                 416898 non-null  object
 22  Latitud                                                  416898 non-null  float64
 23  Longitud                                                 416898 non-null  float64
dtypes: float64(3), int64(4), object(17)
memory usage: 76.3+ MB

In [19]:
denue_2010.sample()

,Nombre de la unidad económica,Razón social,Código de la clase de actividad,Nombre de la clase de actividad,Personal ocupado (estrato),"Calle, avenida, andador, carretera, manzana u otro",Número exterior o km,"Edificio, piso o nivel",Número o letra interior,"Colonia, fraccionamiento, unidad habitacional o barrio",...,Municipio,Localidad,Área geoestadística básica,Manzana,Número de teléfono,Correo electrónico,Sitio en Internet,Tipo de unidad económica,Latitud,Longitud
11567,CAFE INTERNET GRIJALVA,ISRAEL CAMPOR TABLA,561432,SERVICIOS DE ACCESO A COMPUTADORAS,0 A 5 PERSONAS,CAMPO GRIJALVA,47,NaN,NaN,FRACCIONAMIENTO SAN ANTONIO,...,AZCAPOTZALCO,Azcapotzalco,0631,20,5555768270,NaN,NaN,FIJO,19.480689,-99.20996

Lo que unicamente utilizaremos sera:
* Código de la clase de actividad
* Entidad federativa
* Municipio 
* Localidad
* Área geoestadística básica

In [20]:
denue_2010 = denue_2010[["Código de la clase de actividad", "Entidad federativa", "Municipio", "Localidad", "Área geoestadística básica"]]

In [21]:
denue_2010["Entidad federativa"] = "09"

In [22]:
denue_2010["Municipio"] = denue_2010["Municipio"].str.lower()
denue_2010["Localidad"] = denue_2010["Localidad"].str.lower()
denue_2010.sample()

,Código de la clase de actividad,Entidad federativa,Municipio,Localidad,Área geoestadística básica
209600,621211,09,álvaro obregón,álvaro obregón,0173

Carguemos un listado de las alcaldia y sus localidades ya hecho.

In [23]:
lista_loc = pd.read_csv("../../data/raw/2010/localidades_2010.csv", dtype={"ent": str, "mun": str, "loc": str})
lista_loc["nom_mun"] = lista_loc["nom_mun"].str.lower()
lista_loc["nom_loc"] = lista_loc["nom_loc"].str.lower()
lista_loc

    ent  mun                nom_mun   loc                 nom_loc
0    09  002           azcapotzalco  0001            azcapotzalco
1    09  003               coyoacán  0001                coyoacán
2    09  004  cuajimalpa de morelos  0001   cuajimalpa de morelos
3    09  004  cuajimalpa de morelos  0010             cruz blanca
4    09  004  cuajimalpa de morelos  0020    san lorenzo acopilco
..   ..  ...                    ...   ...                     ...
542  09  013             xochimilco  0272  xometitla (tlalitenco)
543  09  014          benito juárez  0001           benito juárez
544  09  015             cuauhtémoc  0001              cuauhtémoc
545  09  016         miguel hidalgo  0001          miguel hidalgo
546  09  017    venustiano carranza  0001     venustiano carranza

[547 rows x 5 columns]

In [24]:
lista_loc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ent      547 non-null    object
 1   mun      547 non-null    object
 2   nom_mun  547 non-null    object
 3   loc      547 non-null    object
 4   nom_loc  547 non-null    object
dtypes: object(5)
memory usage: 21.5+ KB

In [25]:
merge_denue = denue_2010.merge(lista_loc, left_on=["Entidad federativa", "Municipio", "Localidad"] ,right_on=["ent", "nom_mun", "nom_loc"], how="left")

In [26]:
merge_denue[merge_denue["nom_loc"].isna()]["Localidad"]

46054     convento del desierto de los leones
46055     convento del desierto de los leones
46056     convento del desierto de los leones
46057     convento del desierto de los leones
46058     convento del desierto de los leones
                         ...
267918                            tetzontitla
267919                            tetzontitla
267920                            tetzontitla
267921                            tetzontitla
267935                   localidad sin nombre
Name: Localidad, Length: 133, dtype: object

Hay localidades no identificadas, pero esperemos a ver si dentro de nuestras actividades siguen habiendo.

In [27]:
merge_denue.rename(columns={"Código de la clase de actividad": "codigo_act", "Área geoestadística básica": "ageb"}, inplace=True)

In [28]:
denue_2010 = merge_denue[["codigo_act", "ent", "mun", "nom_mun", "loc", "nom_loc", "ageb"]]

In [29]:
denue_2010["cvegeo"] = (denue_2010["ent"] + denue_2010["mun"] + denue_2010["loc"] + denue_2010["ageb"])
denue_2010.sample()

/tmp/ipykernel_155916/3867954123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  denue_2010["cvegeo"] = (denue_2010["ent"] + denue_2010["mun"] + denue_2010["loc"] + denue_2010["ageb"])

        codigo_act ent  mun     nom_mun   loc     nom_loc  ageb         cvegeo
167226      722212  09  007  iztapalapa  0001  iztapalapa  1424  0900700011424

In [30]:
serv_enf_dom = denue_2010[denue_2010["codigo_act"] == 621610]

In [31]:
serv_enf_dom = serv_enf_dom.groupby("cvegeo", as_index=False)["codigo_act"].count()
serv_enf_dom.rename(columns={"codigo_act":"cantidad_serv_enf_dom"}, inplace=True)
serv_enf_dom

           cvegeo  cantidad_serv_enf_dom
0   0900200010307                      1
1   0900300011707                      1
2   0900500011538                      1
3   0900500011561                      1
4   090050001224A                      1
5   0900700012672                      1
6   0900700013488                      1
7   0901000010510                      1
8   0901400010064                      1
9   0901400010083                      1
10  0901400010100                      1
11  0901500011002                      1
12  0901500011337                      1
13  0901500011356                      1
14  0901600010745                      1
15  0901600010783                      1
16  0901700010634                      1

In [32]:
asilos = denue_2010[denue_2010["codigo_act"].isin([623311, 623312])]
asilos

,codigo_act,ent,mun,nom_mun,loc,nom_loc,ageb,cvegeo
12933,623311,09,002,azcapotzalco,0001,azcapotzalco,0345,0900200010345
12934,623311,09,002,azcapotzalco,0001,azcapotzalco,0345,0900200010345
12935,623311,09,002,azcapotzalco,0001,azcapotzalco,081A,090020001081A
33249,623311,09,003,coyoacán,0001,coyoacán,0696,0900300010696
33250,623311,09,003,coyoacán,0001,coyoacán,0111,0900300010111
...,...,...,...,...,...,...,...,...
380117,623311,09,016,miguel hidalgo,0001,miguel hidalgo,1029,0901600011029
380118,623311,09,016,miguel hidalgo,0001,miguel hidalgo,1175,0901600011175
380119,623311,09,016,miguel hidalgo,0001,miguel hidalgo,075A,090160001075A
409046,623311,09,017,venustiano carranza,0001,venustiano carranza,0723,0901700010723
409047,623312,09,017,venustiano carranza,0001,venustiano carranza,0920,0901700010920

In [33]:
asilos = asilos.groupby("cvegeo", as_index=False)["codigo_act"].count()
asilos.rename(columns={"codigo_act":"cantidad_asilos"}, inplace=True)
asilos

           cvegeo  cantidad_asilos
0   0900200010345                2
1   090020001081A                1
2   0900300010111                2
3   0900300010272                1
4   0900300010304                1
..            ...              ...
64  0901600011029                1
65  0901600011156                1
66  0901600011175                1
67  0901700010723                1
68  0901700010920                1

[69 rows x 2 columns]

Como de las agebs que no tienen establecimientos, es porque no hay información en el denue, entonces se infiere que no hay esos servicios, por lo que en esas rellenaremos con 0.

In [34]:
res = pob_ageb_2010.merge(serv_enf_dom, on="cvegeo", how="left")
res["cantidad_serv_enf_dom"] = res["cantidad_serv_enf_dom"].fillna(0)

In [35]:
res

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas,cvegeo,cantidad_serv_enf_dom
0,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0010,0,3424,822.0,0900200010010,0.0
1,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0025,0,5912,974.0,0900200010025,0.0
2,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,003A,0,4638,902.0,090020001003A,0.0
3,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0044,0,5007,993.0,0900200010044,0.0
4,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0097,0,2260,523.0,0900200010097,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2427,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1488,0,1257,51.0,0901700011488,0.0
2428,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1492,0,1013,59.0,0901700011492,0.0
2429,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1505,0,2741,146.0,0901700011505,0.0
2430,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,151A,0,2352,141.0,090170001151A,0.0
2431,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1524,0,4647,537.0,0901700011524,0.0

In [36]:
res = res.merge(asilos, on="cvegeo", how="left")
res["cantidad_asilos"] = res["cantidad_asilos"].fillna(0)
res

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas,cvegeo,cantidad_serv_enf_dom,cantidad_asilos
0,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0010,0,3424,822.0,0900200010010,0.0,0.0
1,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0025,0,5912,974.0,0900200010025,0.0,0.0
2,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,003A,0,4638,902.0,090020001003A,0.0,0.0
3,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0044,0,5007,993.0,0900200010044,0.0,0.0
4,09,Distrito Federal,002,Azcapotzalco,0001,Total AGEB urbana,0097,0,2260,523.0,0900200010097,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2427,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1488,0,1257,51.0,0901700011488,0.0,0.0
2428,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1492,0,1013,59.0,0901700011492,0.0,0.0
2429,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1505,0,2741,146.0,0901700011505,0.0,0.0
2430,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,151A,0,2352,141.0,090170001151A,0.0,0.0
2431,09,Distrito Federal,017,Venustiano Carranza,0001,Total AGEB urbana,1524,0,4647,537.0,0901700011524,0.0,0.0

Saquemos la concentración de poblacion adulta mayor por ageb para la estimación de 2015.

In [37]:
res = res.merge(pob_2010_60mas[["mun", "p_60ymas_mun"]], on="mun", how="left")

In [38]:
res["concentracion"] = res["p_60ymas"] / res["p_60ymas_mun"]

In [39]:
res.to_csv("../../data/processed/results2010.csv")