In [1]:
import pandas as pd

**Obtención de poblacion mayor a 60 años por alcaldía**

In [2]:
pob_2020 = pd.read_excel("../../data/raw/2020/pob_cpv2020_cdmx.xlsx", sheet_name="02", header=5, usecols=["Entidad federativa", "Demarcación territorial", "Sexo","Grupos quinquenales de edad", "Población total1"])
pob_2020.head(5)

,Entidad federativa,Demarcación territorial,Sexo,Grupos quinquenales de edad,Población total1
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,09 Ciudad de México,Total,Total,Total,9209944.0
3,09 Ciudad de México,Total,Total,00-04 años,479904.0
4,09 Ciudad de México,Total,Total,05-09 años,563907.0

In [3]:
pob_2020.drop(index=[0,1], inplace=True)

In [4]:
pob_2020.rename(columns={"Entidad federativa": "entidad", "Demarcación territorial": "mun", "Sexo":"sexo", "Grupos quinquenales de edad": "rangos_edad", "Población total1": "poblacion"}, inplace=True)

In [5]:
pob_2020 = pob_2020[(pob_2020["mun"] != "Total") & (pob_2020["sexo"] == "Total")]
pob_2020.sample(5)

,entidad,mun,sexo,rangos_edad,poblacion
368,09 Ciudad de México,004 Cuajimalpa de Morelos,Total,100 años y más,24.0
904,09 Ciudad de México,011 Tláhuac,Total,20-24 años,33573.0
714,09 Ciudad de México,008 La Magdalena Contreras,Total,No especificado,43.0
419,09 Ciudad de México,015 Cuauhtémoc,Total,10-14 años,29907.0
838,09 Ciudad de México,009 Milpa Alta,Total,35-39 años,10995.0

In [6]:
rangos_edad = ["60-64 años", "65-69 años", "70-74 años", "75-79 años", "80-84 años", "85-89 años", "90-94 años", "95-99 años", "100 años y más"]

In [7]:
pob_2020 = pob_2020[pob_2020["rangos_edad"].isin(rangos_edad)]
pob_2020.head(5)

                entidad                 mun   sexo rangos_edad  poblacion
84  09 Ciudad de México  010 Álvaro Obregón  Total  60-64 años    38506.0
85  09 Ciudad de México  010 Álvaro Obregón  Total  65-69 años    29503.0
86  09 Ciudad de México  010 Álvaro Obregón  Total  70-74 años    21797.0
87  09 Ciudad de México  010 Álvaro Obregón  Total  75-79 años    14182.0
88  09 Ciudad de México  010 Álvaro Obregón  Total  80-84 años     9657.0

In [8]:
pob_2020["entidad"] = pob_2020["entidad"].str.extract("(\d*)\s")
pob_2020["mun"] = pob_2020["mun"].str.extract("(\d*)\s")
pob_2020.head(5)

   entidad  mun   sexo rangos_edad  poblacion
84      09  010  Total  60-64 años    38506.0
85      09  010  Total  65-69 años    29503.0
86      09  010  Total  70-74 años    21797.0
87      09  010  Total  75-79 años    14182.0
88      09  010  Total  80-84 años     9657.0

In [9]:
pob_2020_60mas = pob_2020.groupby(["entidad","mun"], as_index=False)["poblacion"].sum()
pob_2020_60mas.rename(columns={"poblacion": "p_60ymas_mun"}, inplace=True)
pob_2020_60mas

   entidad  mun  p_60ymas_mun
0       09  002       78650.0
1       09  003      126592.0
2       09  004       25803.0
3       09  005      203469.0
4       09  006       70907.0
5       09  007      262064.0
6       09  008       38073.0
7       09  009       16437.0
8       09  010      122319.0
9       09  011       46196.0
10      09  012      108894.0
11      09  013       60987.0
12      09  014       87344.0
13      09  015       93809.0
14      09  016       71111.0
15      09  017       78964.0

**Obtención de población mayor a 60 años por AGEB**

Como podemos ver los campos que utilizaremos seran:
* Clave entidad federativa - ENTIDAD
* Entidad federativa - NOM_ENT
* Clave de municipio o demarcación territorial - MUN
* Municipio o demarcación territorial - NOM_MUN
* Clave de localidad - LOC
* Localidad	- NOM_LOC
* Clave del AGEB - AGEB
* Clave manzana - MZA
* Población total - POBTOT
* Población de 60 años y más - P_60YMAS

In [10]:
pob_ageb_2020 = pd.read_csv("../../data/raw/2020/pob_ageb_cpv2020_cdmx.csv", dtype={"ENTIDAD":str, "MUN": str, "LOC": str})
pob_ageb_2020

,ENTIDAD,NOM_ENT,MUN,NOM_MUN,LOC,NOM_LOC,AGEB,MZA,POBTOT,POBFEM,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCINT,VPH_SINTIC
0,09,Ciudad de México,000,Total de la entidad Ciudad de México,0000,Total de la entidad,0000,0,9209944,4805017,...,1898265,2536523,2084156,1290811,957162,568827,46172,77272,561128,10528
1,09,Ciudad de México,002,Azcapotzalco,0000,Total del municipio,0000,0,432205,227255,...,96128,123961,105899,66399,50965,31801,1661,2869,22687,322
2,09,Ciudad de México,002,Azcapotzalco,0001,Total de la localidad urbana,0000,0,432205,227255,...,96128,123961,105899,66399,50965,31801,1661,2869,22687,322
3,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0010,0,3183,1695,...,741,772,692,313,221,145,8,14,148,5
4,09,Ciudad de México,002,Azcapotzalco,0001,Azcapotzalco,0010,1,159,86,...,45,42,39,18,13,6,*,0,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68936,09,Ciudad de México,017,Venustiano Carranza,0001,Venustiano Carranza,1524,21,106,58,...,23,27,24,12,12,9,0,0,6,0
68937,09,Ciudad de México,017,Venustiano Carranza,0001,Venustiano Carranza,1524,22,107,55,...,35,37,34,14,11,11,0,*,5,0
68938,09,Ciudad de México,017,Venustiano Carranza,0001,Venustiano Carranza,1524,23,246,116,...,40,68,48,22,12,8,*,*,23,*
68939,09,Ciudad de México,017,Venustiano Carranza,0001,Venustiano Carranza,1524,24,158,78,...,30,37,29,16,5,9,0,4,12,0
68940,09,Ciudad de México,017,Venustiano Carranza,0001,Venustiano Carranza,1524,25,474,247,...,71,123,88,33,31,23,4,3,33,0

In [11]:
pob_ageb_2020.rename(columns={"ENTIDAD": "entidad", "NOM_ENT": "nom_ent", "MUN": "mun", "NOM_MUN": "nom_mun", "LOC": "loc", "NOM_LOC": "nom_loc", "AGEB": "ageb", "MZA": "mza", "POBTOT": "pobtot", "P_60YMAS": "p_60ymas"}, inplace=True)

In [12]:
pob_ageb_2020 = pob_ageb_2020[["entidad", "nom_ent", "mun", "nom_mun", "loc", "nom_loc", "ageb", "mza", "pobtot", "p_60ymas"]]
pob_ageb_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68941 entries, 0 to 68940
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   entidad   68941 non-null  object
 1   nom_ent   68941 non-null  object
 2   mun       68941 non-null  object
 3   nom_mun   68941 non-null  object
 4   loc       68941 non-null  object
 5   nom_loc   68941 non-null  object
 6   ageb      68941 non-null  object
 7   mza       68941 non-null  int64
 8   pobtot    68941 non-null  int64
 9   p_60ymas  68941 non-null  object
dtypes: int64(2), object(8)
memory usage: 5.3+ MB

In [13]:
pob_ageb_2020["entidad"] = pob_ageb_2020["entidad"].str.zfill(2)
pob_ageb_2020["mun"] = pob_ageb_2020["mun"].str.zfill(3)
pob_ageb_2020["loc"] = pob_ageb_2020["loc"].str.zfill(4)
pob_ageb_2020["ageb"] = pob_ageb_2020["ageb"].str.zfill(4)

/tmp/ipykernel_148562/3576184769.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2020["entidad"] = pob_ageb_2020["entidad"].str.zfill(2)
/tmp/ipykernel_148562/3576184769.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2020["mun"] = pob_ageb_2020["mun"].str.zfill(3)
/tmp/ipykernel_148562/3576184769.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2020["loc"] = pob_ageb_2020["loc"].str.zfill(4)
/tmp/ipykernel_148562/3576184769.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pob_ageb_2020["ageb"] = pob_ageb_2020["ageb"].str.zfill(4)

In [14]:
pob_ageb_2020 = pob_ageb_2020[(pob_ageb_2020.ageb != "0000") & (pob_ageb_2020.mza == 0)]
pob_ageb_2020.sample(5)

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas
9862,09,Ciudad de México,005,Gustavo A. Madero,0001,Total AGEB urbana,0192,0,5552,921
42574,09,Ciudad de México,010,Álvaro Obregón,0001,Total AGEB urbana,1434,0,5554,926
23451,09,Ciudad de México,007,Iztapalapa,0001,Total AGEB urbana,077A,0,4047,624
40469,09,Ciudad de México,010,Álvaro Obregón,0001,Total AGEB urbana,0385,0,3058,342
66954,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,0795,0,201,39

Pasemos p_60ymas a numerico para poder operarla.

In [15]:
pob_ageb_2020["p_60ymas"] = pd.to_numeric(pob_ageb_2020["p_60ymas"], errors="coerce")

In [16]:
pob_ageb_2020[pob_ageb_2020["p_60ymas"].isna()]

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas
3008,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,1076,0,1,NaN
14154,09,Ciudad de México,005,Gustavo A. Madero,0001,Total AGEB urbana,1928,0,14,NaN
19579,09,Ciudad de México,006,Iztacalco,0001,Total AGEB urbana,0467,0,20,NaN
26505,09,Ciudad de México,007,Iztapalapa,0001,Total AGEB urbana,2121,0,146,NaN
45218,09,Ciudad de México,010,Álvaro Obregón,0001,Total AGEB urbana,2381,0,21,NaN
46550,09,Ciudad de México,011,Tláhuac,0001,Total AGEB urbana,0768,0,18,NaN
51886,09,Ciudad de México,012,Tlalpan,0001,Total AGEB urbana,1759,0,6,NaN
54548,09,Ciudad de México,013,Xochimilco,0001,Total AGEB urbana,032A,0,13,NaN
56388,09,Ciudad de México,013,Xochimilco,0001,Total AGEB urbana,1277,0,55,NaN
56907,09,Ciudad de México,013,Xochimilco,0001,Total AGEB urbana,1578,0,35,NaN
59425,09,Ciudad de México,015,Cuauhtémoc,0001,Total AGEB urbana,0057,0,24,NaN
62364,09,Ciudad de México,016,Miguel Hidalgo,0001,Total AGEB urbana,0016,0,7,NaN
62392,09,Ciudad de México,016,Miguel Hidalgo,0001,Total AGEB urbana,0035,0,2,NaN
62841,09,Ciudad de México,016,Miguel Hidalgo,0001,Total AGEB urbana,0228,0,2,NaN
63510,09,Ciudad de México,016,Miguel Hidalgo,0001,Total AGEB urbana,0533,0,7,NaN
64492,09,Ciudad de México,016,Miguel Hidalgo,0001,Total AGEB urbana,1071,0,2,NaN
66536,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,0598,0,4,NaN

Antes de ver que haremos con esos NaN haremos la clave unica geoestadítica por ageb

In [17]:
pob_ageb_2020["cvegeo"] = (pob_ageb_2020["entidad"] + pob_ageb_2020["mun"] + pob_ageb_2020["loc"] + pob_ageb_2020["ageb"])

In [18]:
pob_ageb_2020.sample(5)

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas,cvegeo
20844,09,Ciudad de México,006,Iztacalco,0001,Total AGEB urbana,0984,0,1628,481.0,0900600010984
57902,09,Ciudad de México,014,Benito Juárez,0001,Total AGEB urbana,044A,0,4368,962.0,090140001044A
16330,09,Ciudad de México,005,Gustavo A. Madero,0001,Total AGEB urbana,2767,0,5406,580.0,0900500012767
42674,09,Ciudad de México,010,Álvaro Obregón,0001,Total AGEB urbana,1472,0,3788,398.0,0901000011472
11589,09,Ciudad de México,005,Gustavo A. Madero,0001,Total AGEB urbana,092A,0,2904,661.0,090050001092A

**Obtención de servicios DENUE por AGEB**

*Servicios DENUE 2020* 
Clave - Descripción de categoría
* 621610 - Servicios de enfermería a domicilio
* 623311 - Asilos y otras residencias del sector privado para el cuidado de ancianos
* 623312 - Asilos y otras residencias del sector público para el cuidado de ancianos

In [19]:
denue_2020 = pd.read_csv("../../data/raw/2020/denue2020.csv", encoding="latin-1")
denue_2020.info()

/tmp/ipykernel_148562/1098980384.py:1: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  denue_2020 = pd.read_csv("../../data/raw/2020/denue2020.csv", encoding="latin-1")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474328 entries, 0 to 474327
Data columns (total 41 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          474328 non-null  int64
 1   nom_estab   474327 non-null  object
 2   raz_social  103549 non-null  object
 3   codigo_act  474328 non-null  int64
 4   nombre_act  474328 non-null  object
 5   per_ocu     474328 non-null  object
 6   tipo_vial   472033 non-null  object
 7   nom_vial    474275 non-null  object
 8   tipo_v_e_1  464812 non-null  object
 9   nom_v_e_1   466167 non-null  object
 10  tipo_v_e_2  464807 non-null  object
 11  nom_v_e_2   466147 non-null  object
 12  tipo_v_e_3  465076 non-null  object
 13  nom_v_e_3   466363 non-null  object
 14  numero_ext  402706 non-null  float64
 15  letra_ext   186163 non-null  object
 16  edificio    94255 non-null   object
 17  edificio_e  94973 non-null   object
 18  numero_int  204667 non-null  float64
 19  letra_int   45680 non-null   object
 20  tipo_asent  472934 non-null  object
 21  nomb_asent  474035 non-null  object
 22  tipoCenCom  86011 non-null   object
 23  nom_CenCom  85265 non-null   object
 24  num_local   84396 non-null   object
 25  cod_postal  470963 non-null  float64
 26  cve_ent     474328 non-null  int64
 27  entidad     474328 non-null  object
 28  cve_mun     474328 non-null  int64
 29  municipio   474328 non-null  object
 30  cve_loc     474328 non-null  int64
 31  localidad   474328 non-null  object
 32  ageb        474328 non-null  object
 33  manzana     474328 non-null  int64
 34  telefono    127900 non-null  object
 35  correoelec  81180 non-null   object
 36  www         40741 non-null   object
 37  tipoUniEco  474328 non-null  object
 38  latitud     474328 non-null  float64
 39  longitud    474328 non-null  float64
 40  fecha_alta  474328 non-null  object
dtypes: float64(5), int64(6), object(30)
memory usage: 148.4+ MB

In [20]:
denue_2020.sample()

,id,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,nom_v_e_1,...,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta
145157,729601,LIMPI MART,NaN,467115,Comercio al por menor de artículos para la lim...,0 a 5 personas,CALLE,ALFONSO ALARCON,CALLE,URBANO ESPINOZA,...,Iztapalapa,464,17,5557455453,NaN,NaN,Fijo,19.376522,-99.02342,2014-12

Lo que unicamente utilizaremos sera:
* Código de la clase de actividad
* Entidad federativa
* Municipio 
* Localidad
* Área geoestadística básica

In [21]:
denue_2020 = denue_2020[["codigo_act", "cve_ent", "cve_mun", "cve_loc", "ageb"]]
denue_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474328 entries, 0 to 474327
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   codigo_act  474328 non-null  int64
 1   cve_ent     474328 non-null  int64
 2   cve_mun     474328 non-null  int64
 3   cve_loc     474328 non-null  int64
 4   ageb        474328 non-null  object
dtypes: int64(4), object(1)
memory usage: 18.1+ MB

Hay localidades no identificadas, pero esperemos a ver si dentro de nuestras actividades siguen habiendo.

In [22]:
denue_2020.rename(columns={"cve_ent":"entidad", "cve_mun":"mun", "cve_loc":"loc"}, inplace=True)

In [23]:
denue_2020["entidad"] = denue_2020["entidad"].astype(str).str.zfill(2)
denue_2020["mun"] = denue_2020["mun"].astype(str).str.zfill(3)
denue_2020["loc"] = denue_2020["loc"].astype(str).str.zfill(4)
denue_2020["ageb"] = denue_2020["ageb"].str.zfill(4)
denue_2020.sample()

    codigo_act entidad  mun   loc  ageb
10      115111      09  015  0001  1464

In [24]:
denue_2020["cvegeo"] = (denue_2020["entidad"] + denue_2020["mun"] + denue_2020["loc"] + denue_2020["ageb"])
denue_2020.sample()

        codigo_act entidad  mun   loc  ageb         cvegeo
231843      467111      09  003  0001  1181  0900300011181

In [25]:
serv_enf_dom = denue_2020[denue_2020["codigo_act"] == 621610]

In [26]:
serv_enf_dom = serv_enf_dom.groupby("cvegeo", as_index=False)["codigo_act"].count()
serv_enf_dom.rename(columns={"codigo_act":"cantidad_serv_enf_dom"}, inplace=True)
serv_enf_dom

           cvegeo  cantidad_serv_enf_dom
0   0900300011020                      1
1   0900600010382                      1
2   0900700012174                      1
3   0901100010679                      1
4   0901200010163                      1
5   0901200011481                      1
6   0901400010257                      1
7   0901400010276                      1
8   0901400010990                      1
9   0901500011341                      1
10  0901600010660                      1
11  0901700011261                      1

In [27]:
asilos = denue_2020[denue_2020["codigo_act"].isin([623311, 623312])]
asilos

        codigo_act entidad  mun   loc  ageb         cvegeo
315050      623311      09  014  0001  0632  0901400010632
315089      623311      09  015  0001  1017  0901500011017
315134      623312      09  014  0001  0384  0901400010384
315143      623312      09  003  0001  0094  0900300010094
315148      623312      09  014  0001  0204  0901400010204
...            ...     ...  ...   ...   ...            ...
336639      623311      09  014  0001  005A  090140001005A
336893      623312      09  008  0001  0283  0900800010283
337161      623311      09  014  0001  0261  0901400010261
337233      623311      09  008  0001  0283  0900800010283
337372      623311      09  002  0001  0699  0900200010699

[108 rows x 6 columns]

In [28]:
asilos = asilos.groupby("cvegeo", as_index=False)["codigo_act"].count()
asilos.rename(columns={"codigo_act":"cantidad_asilos"}, inplace=True)
asilos

           cvegeo  cantidad_asilos
0   0900200010345                2
1   0900200010491                1
2   0900200010699                1
3   0900200010792                1
4   0900200010858                1
..            ...              ...
90  0901600010694                1
91  0901600010707                1
92  0901600010942                1
93  0901600011156                1
94  0901600011175                1

[95 rows x 2 columns]

Como de las agebs que no tienen establecimientos, es porque no hay información en el denue, entonces se infiere que no hay esos servicios, por lo que en esas rellenaremos con 0.

In [29]:
res = pob_ageb_2020.merge(serv_enf_dom, on="cvegeo", how="left")
res["cantidad_serv_enf_dom"] = res["cantidad_serv_enf_dom"].fillna(0)

In [30]:
res

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas,cvegeo,cantidad_serv_enf_dom
0,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0010,0,3183,816.0,0900200010010,0.0
1,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0025,0,5593,1293.0,0900200010025,0.0
2,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,003A,0,4235,931.0,090020001003A,0.0
3,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0044,0,4768,1132.0,0900200010044,0.0
4,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0097,0,2176,562.0,0900200010097,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2428,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1488,0,1079,115.0,0901700011488,0.0
2429,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1492,0,900,94.0,0901700011492,0.0
2430,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1505,0,2513,299.0,0901700011505,0.0
2431,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,151A,0,2248,311.0,090170001151A,0.0
2432,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1524,0,4295,706.0,0901700011524,0.0

In [31]:
res = res.merge(asilos, on="cvegeo", how="left")
res["cantidad_asilos"] = res["cantidad_asilos"].fillna(0)
res

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas,cvegeo,cantidad_serv_enf_dom,cantidad_asilos
0,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0010,0,3183,816.0,0900200010010,0.0,0.0
1,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0025,0,5593,1293.0,0900200010025,0.0,0.0
2,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,003A,0,4235,931.0,090020001003A,0.0,0.0
3,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0044,0,4768,1132.0,0900200010044,0.0,0.0
4,09,Ciudad de México,002,Azcapotzalco,0001,Total AGEB urbana,0097,0,2176,562.0,0900200010097,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2428,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1488,0,1079,115.0,0901700011488,0.0,0.0
2429,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1492,0,900,94.0,0901700011492,0.0,0.0
2430,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1505,0,2513,299.0,0901700011505,0.0,0.0
2431,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,151A,0,2248,311.0,090170001151A,0.0,0.0
2432,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1524,0,4295,706.0,0901700011524,0.0,0.0

Saquemos la concentración de poblacion adulta mayor por ageb para la estimación de 2015.

In [32]:
res = res.merge(pob_2020_60mas[["mun", "p_60ymas_mun"]], on="mun", how="left")

In [33]:
res["concentracion"] = res["p_60ymas"] / res["p_60ymas_mun"]

In [34]:
res.sample(5)

,entidad,nom_ent,mun,nom_mun,loc,nom_loc,ageb,mza,pobtot,p_60ymas,cvegeo,cantidad_serv_enf_dom,cantidad_asilos,p_60ymas_mun,concentracion
1272,09,Ciudad de México,010,Álvaro Obregón,0001,Total AGEB urbana,0192,0,654,144.0,0901000010192,0.0,0.0,122319.0,0.001177
2018,09,Ciudad de México,015,Cuauhtémoc,0001,Total AGEB urbana,0201,0,1612,363.0,0901500010201,0.0,0.0,93809.0,0.003870
1619,09,Ciudad de México,012,Tlalpan,0001,Total AGEB urbana,0623,0,3257,547.0,0901200010623,0.0,0.0,108894.0,0.005023
2250,09,Ciudad de México,016,Miguel Hidalgo,0001,Total AGEB urbana,1052,0,848,257.0,0901600011052,0.0,0.0,71111.0,0.003614
2404,09,Ciudad de México,017,Venustiano Carranza,0001,Total AGEB urbana,1242,0,4012,761.0,0901700011242,0.0,0.0,78964.0,0.009637

In [ ]:
res.to_csv("../../data/processed/results2020.csv")